window.MIDNIGHT_BOOKS = [
  {
    "id": "harry-potter-harry-potter-and-the-philosopher-s-stone",
    "title": "Harry Potter and the Philosopher's Stone",
    "author": "J. K. Rowling",
    "collection": "Harry Potter",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "harry-potter-harry-potter-and-the-philosopher-s-stone.epub"
  },
  {
    "id": "harry-potter-harry-potter-and-the-chamber-of-secrets",
    "title": "Harry Potter and the Chamber of Secrets",
    "author": "J. K. Rowling",
    "collection": "Harry Potter",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "harry-potter-harry-potter-and-the-chamber-of-secrets.epub"
  },
  {
    "id": "harry-potter-harry-potter-and-the-prisoner-of-azkaban",
    "title": "Harry Potter and the Prisoner of Azkaban",
    "author": "J. K. Rowling",
    "collection": "Harry Potter",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "harry-potter-harry-potter-and-the-prisoner-of-azkaban.epub"
  },
  {
    "id": "harry-potter-harry-potter-and-the-goblet-of-fire",
    "title": "Harry Potter and the Goblet of Fire",
    "author": "J. K. Rowling",
    "collection": "Harry Potter",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 4,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "harry-potter-harry-potter-and-the-goblet-of-fire.epub"
  },
  {
    "id": "harry-potter-harry-potter-and-the-order-of-the-phoenix",
    "title": "Harry Potter and the Order of the Phoenix",
    "author": "J. K. Rowling",
    "collection": "Harry Potter",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 5,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "harry-potter-harry-potter-and-the-order-of-the-phoenix.epub"
  },
  {
    "id": "harry-potter-harry-potter-and-the-half-blood-prince",
    "title": "Harry Potter and the Half-Blood Prince",
    "author": "J. K. Rowling",
    "collection": "Harry Potter",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 6,
    "status": "to-read",
    "favorite": false,
    "spine": "charcoal",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "harry-potter-harry-potter-and-the-half-blood-prince.epub"
  },
  {
    "id": "harry-potter-harry-potter-and-the-deathly-hallows",
    "title": "Harry Potter and the Deathly Hallows",
    "author": "J. K. Rowling",
    "collection": "Harry Potter",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 7,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "harry-potter-harry-potter-and-the-deathly-hallows.epub"
  },
  {
    "id": "harry-potter-harry-potter-and-the-cursed-child",
    "title": "Harry Potter and the Cursed Child",
    "author": "J. K. Rowling",
    "collection": "Harry Potter",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 8,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "harry-potter-harry-potter-and-the-cursed-child.epub"
  },
  {
    "id": "the-witcher-the-road-with-no-return",
    "title": "The Road with No Return",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-the-road-with-no-return.epub"
  },
  {
    "id": "the-witcher-the-last-wish",
    "title": "The Last Wish",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-the-last-wish.epub"
  },
  {
    "id": "the-witcher-sword-of-destiny",
    "title": "Sword of Destiny",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-sword-of-destiny.epub"
  },
  {
    "id": "the-witcher-blood-of-elves",
    "title": "Blood of Elves",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 4,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-blood-of-elves.epub"
  },
  {
    "id": "the-witcher-the-time-of-contempt",
    "title": "The Time of Contempt",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 5,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-the-time-of-contempt.epub"
  },
  {
    "id": "the-witcher-baptism-of-fire",
    "title": "Baptism of Fire",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 6,
    "status": "to-read",
    "favorite": false,
    "spine": "charcoal",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-baptism-of-fire.epub"
  },
  {
    "id": "the-witcher-the-tower-of-the-swallow",
    "title": "The Tower of the Swallow",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 7,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-the-tower-of-the-swallow.epub"
  },
  {
    "id": "the-witcher-the-lady-of-the-lake",
    "title": "The Lady of the Lake",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 8,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-the-lady-of-the-lake.epub"
  },
  {
    "id": "the-witcher-season-of-storms",
    "title": "Season of Storms",
    "author": "Andrzej Sapkowski",
    "collection": "The Witcher",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 9,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-witcher-season-of-storms.epub"
  },
  {
    "id": "the-vampire-diaries-the-awakening",
    "title": "The Awakening",
    "author": "L. J. Smith",
    "collection": "The Vampire Diaries",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-vampire-diaries-the-awakening.epub"
  },
  {
    "id": "the-vampire-diaries-the-struggle",
    "title": "The Struggle",
    "author": "L. J. Smith",
    "collection": "The Vampire Diaries",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-vampire-diaries-the-struggle.epub"
  },
  {
    "id": "the-vampire-diaries-the-fury",
    "title": "The Fury",
    "author": "L. J. Smith",
    "collection": "The Vampire Diaries",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-vampire-diaries-the-fury.epub"
  },
  {
    "id": "the-vampire-diaries-dark-reunion",
    "title": "Dark Reunion",
    "author": "L. J. Smith",
    "collection": "The Vampire Diaries",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 4,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-vampire-diaries-dark-reunion.epub"
  },
  {
    "id": "the-vampire-diaries-the-return-nightfall",
    "title": "The Return: Nightfall",
    "author": "L. J. Smith",
    "collection": "The Vampire Diaries",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 5,
    "status": "to-read",
    "favorite": false,
    "spine": "charcoal",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-vampire-diaries-the-return-nightfall.epub"
  },
  {
    "id": "the-vampire-diaries-the-return-shadow-souls",
    "title": "The Return: Shadow Souls",
    "author": "L. J. Smith",
    "collection": "The Vampire Diaries",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 6,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-vampire-diaries-the-return-shadow-souls.epub"
  },
  {
    "id": "the-vampire-diaries-the-return",
    "title": "The Return",
    "author": "L. J. Smith",
    "collection": "The Vampire Diaries",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 7,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-vampire-diaries-the-return.epub"
  },
  {
    "id": "the-vampire-diaries-the-hunters-phantom",
    "title": "The Hunters: Phantom",
    "author": "L. J. Smith",
    "collection": "The Vampire Diaries",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 8,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-vampire-diaries-the-hunters-phantom.epub"
  },
  {
    "id": "the-originals-the-rise",
    "title": "The Rise",
    "author": "Julie Plec",
    "collection": "The Originals",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-originals-the-rise.epub"
  },
  {
    "id": "the-originals-the-loss",
    "title": "The Loss",
    "author": "Julie Plec",
    "collection": "The Originals",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-originals-the-loss.epub"
  },
  {
    "id": "the-originals-the-resurrection",
    "title": "The Resurrection",
    "author": "Julie Plec",
    "collection": "The Originals",
    "wing": "Supernatural",
    "genre": "Supernatural",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-originals-the-resurrection.epub"
  },
  {
    "id": "the-lord-of-the-rings-the-fellowship-of-the-ring",
    "title": "The Fellowship of the Ring",
    "author": "J. R. R. Tolkien",
    "collection": "The Lord of the Rings",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-lord-of-the-rings-the-fellowship-of-the-ring.epub"
  },
  {
    "id": "the-lord-of-the-rings-the-two-towers",
    "title": "The Two Towers",
    "author": "J. R. R. Tolkien",
    "collection": "The Lord of the Rings",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "charcoal",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-lord-of-the-rings-the-two-towers.epub"
  },
  {
    "id": "the-lord-of-the-rings-the-return-of-the-king",
    "title": "The Return of the King",
    "author": "J. R. R. Tolkien",
    "collection": "The Lord of the Rings",
    "wing": "Fantasy",
    "genre": "Fantasy",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "the-lord-of-the-rings-the-return-of-the-king.epub"
  },
  {
    "id": "silo-silo-the-complete-series",
    "title": "Silo — The Complete Series",
    "author": "Hugh Howey",
    "collection": "Silo",
    "wing": "Dystopian",
    "genre": "Dystopian",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "silo-silo-the-complete-series.epub"
  },
  {
    "id": "bridgerton-the-duke-and-i",
    "title": "The Duke and I",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-the-duke-and-i.epub"
  },
  {
    "id": "bridgerton-the-viscount-who-loved-me",
    "title": "The Viscount Who Loved Me",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-the-viscount-who-loved-me.epub"
  },
  {
    "id": "bridgerton-an-offer-from-a-gentleman",
    "title": "An Offer From a Gentleman",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-an-offer-from-a-gentleman.epub"
  },
  {
    "id": "bridgerton-romancing-mister-bridgerton",
    "title": "Romancing Mister Bridgerton",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 4,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-romancing-mister-bridgerton.epub"
  },
  {
    "id": "bridgerton-to-sir-phillip-with-love",
    "title": "To Sir Phillip, With Love",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 5,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-to-sir-phillip-with-love.epub"
  },
  {
    "id": "bridgerton-when-he-was-wicked",
    "title": "When He Was Wicked",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 6,
    "status": "to-read",
    "favorite": false,
    "spine": "charcoal",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-when-he-was-wicked.epub"
  },
  {
    "id": "bridgerton-it-s-in-his-kiss",
    "title": "It's in His Kiss",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 7,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-it-s-in-his-kiss.epub"
  },
  {
    "id": "bridgerton-on-the-way-to-the-wedding",
    "title": "On the Way to the Wedding",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 8,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-on-the-way-to-the-wedding.epub"
  },
  {
    "id": "bridgerton-the-bridgertons-happily-ever-after",
    "title": "The Bridgertons: Happily Ever After",
    "author": "Julia Quinn",
    "collection": "Bridgerton",
    "wing": "Romance",
    "genre": "Romance",
    "order": 9,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "bridgerton-the-bridgertons-happily-ever-after.epub"
  },
  {
    "id": "arsene-lupin-the-extraordinary-adventures-of-arsene-lupin-gentleman-burglar",
    "title": "The Extraordinary Adventures of Arsène Lupin, Gentleman-Burglar",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-extraordinary-adventures-of-arsene-lupin-gentleman-burglar.epub"
  },
  {
    "id": "arsene-lupin-arsene-lupin-vs-herlock-sholmes",
    "title": "Arsène Lupin vs. Herlock Sholmes",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-arsene-lupin-vs-herlock-sholmes.epub"
  },
  {
    "id": "arsene-lupin-arsene-lupin",
    "title": "Arsène Lupin",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-arsene-lupin.epub"
  },
  {
    "id": "arsene-lupin-the-hollow-needle",
    "title": "The Hollow Needle",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 4,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-hollow-needle.epub"
  },
  {
    "id": "arsene-lupin-813",
    "title": "813",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 5,
    "status": "to-read",
    "favorite": false,
    "spine": "charcoal",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-813.epub"
  },
  {
    "id": "arsene-lupin-the-crystal-stopper",
    "title": "The Crystal Stopper",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 6,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-crystal-stopper.epub"
  },
  {
    "id": "arsene-lupin-the-confessions-of-arsene-lupin",
    "title": "The Confessions of Arsène Lupin",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 7,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-confessions-of-arsene-lupin.epub"
  },
  {
    "id": "arsene-lupin-the-woman-of-mystery",
    "title": "The Woman of Mystery",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 8,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-woman-of-mystery.epub"
  },
  {
    "id": "arsene-lupin-the-golden-triangle",
    "title": "The Golden Triangle",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 9,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-golden-triangle.epub"
  },
  {
    "id": "arsene-lupin-the-secret-of-sarek",
    "title": "The Secret of Sarek",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 10,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-secret-of-sarek.epub"
  },
  {
    "id": "arsene-lupin-the-teeth-of-the-tiger",
    "title": "The Teeth of the Tiger",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 11,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-teeth-of-the-tiger.epub"
  },
  {
    "id": "arsene-lupin-the-eight-strokes-of-the-clock",
    "title": "The Eight Strokes of the Clock",
    "author": "Maurice Leblanc",
    "collection": "Arsène Lupin",
    "wing": "Mystery",
    "genre": "Mystery",
    "order": 12,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "arsene-lupin-the-eight-strokes-of-the-clock.epub"
  },
  {
    "id": "t-h-white-mistress-masham-s-repose",
    "title": "Mistress Masham's Repose",
    "author": "T. H. White",
    "collection": "T. H. White",
    "wing": "Classics & Fantasy",
    "genre": "Classics & Fantasy",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "charcoal",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "t-h-white-mistress-masham-s-repose.epub"
  },
  {
    "id": "t-h-white-darkness-at-pemberley",
    "title": "Darkness at Pemberley",
    "author": "T. H. White",
    "collection": "T. H. White",
    "wing": "Classics & Fantasy",
    "genre": "Classics & Fantasy",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "t-h-white-darkness-at-pemberley.epub"
  },
  {
    "id": "t-h-white-the-candle-in-the-wind",
    "title": "The Candle in the Wind",
    "author": "T. H. White",
    "collection": "T. H. White",
    "wing": "Classics & Fantasy",
    "genre": "Classics & Fantasy",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "t-h-white-the-candle-in-the-wind.epub"
  },
  {
    "id": "t-h-white-they-winter-abroad",
    "title": "They Winter Abroad",
    "author": "T. H. White",
    "collection": "T. H. White",
    "wing": "Classics & Fantasy",
    "genre": "Classics & Fantasy",
    "order": 4,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "t-h-white-they-winter-abroad.epub"
  },
  {
    "id": "t-h-white-the-witch-in-the-wood",
    "title": "The Witch in the Wood",
    "author": "T. H. White",
    "collection": "T. H. White",
    "wing": "Classics & Fantasy",
    "genre": "Classics & Fantasy",
    "order": 5,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "t-h-white-the-witch-in-the-wood.epub"
  },
  {
    "id": "t-h-white-the-sword-in-the-stone",
    "title": "The Sword in the Stone",
    "author": "T. H. White",
    "collection": "T. H. White",
    "wing": "Classics & Fantasy",
    "genre": "Classics & Fantasy",
    "order": 6,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "t-h-white-the-sword-in-the-stone.epub"
  },
  {
    "id": "t-h-white-the-once-and-future-king",
    "title": "The Once and Future King",
    "author": "T. H. White",
    "collection": "T. H. White",
    "wing": "Classics & Fantasy",
    "genre": "Classics & Fantasy",
    "order": 7,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "t-h-white-the-once-and-future-king.epub"
  },
  {
    "id": "t-h-white-the-ill-made-knight",
    "title": "The Ill-Made Knight",
    "author": "T. H. White",
    "collection": "T. H. White",
    "wing": "Classics & Fantasy",
    "genre": "Classics & Fantasy",
    "order": 8,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "t-h-white-the-ill-made-knight.epub"
  },
  {
    "id": "mind-self-the-art-of-thinking-clearly",
    "title": "The Art of Thinking Clearly",
    "author": "Rolf Dobelli",
    "collection": "Mind & Self",
    "wing": "Mind & Self",
    "genre": "Mind & Self",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "charcoal",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "mind-self-the-art-of-thinking-clearly.epub"
  },
  {
    "id": "mind-self-the-power-of-now",
    "title": "The Power of Now",
    "author": "Eckhart Tolle",
    "collection": "Mind & Self",
    "wing": "Mind & Self",
    "genre": "Mind & Self",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "mind-self-the-power-of-now.epub"
  },
  {
    "id": "mind-self-how-to-win-friends-and-influence-people",
    "title": "How to Win Friends and Influence People",
    "author": "Dale Carnegie",
    "collection": "Mind & Self",
    "wing": "Mind & Self",
    "genre": "Mind & Self",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "medium",
    "format": "DOC",
    "file": null,
    "private": true,
    "storagePath": null
  },
  {
    "id": "mind-self-change-your-brain-change-your-body",
    "title": "Change Your Brain, Change Your Body",
    "author": "Daniel G. Amen",
    "collection": "Mind & Self",
    "wing": "Mind & Self",
    "genre": "Mind & Self",
    "order": 4,
    "status": "to-read",
    "favorite": false,
    "spine": "wine",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "mind-self-change-your-brain-change-your-body.epub"
  },
  {
    "id": "mind-self-flash-foresight",
    "title": "Flash Foresight",
    "author": "Daniel Burrus & John David Mann",
    "collection": "Mind & Self",
    "wing": "Mind & Self",
    "genre": "Mind & Self",
    "order": 5,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "mind-self-flash-foresight.epub"
  },
  {
    "id": "mind-self-unleash-the-power-of-the-female-brain",
    "title": "Unleash the Power of the Female Brain",
    "author": "Daniel G. Amen",
    "collection": "Mind & Self",
    "wing": "Mind & Self",
    "genre": "Mind & Self",
    "order": 6,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "mind-self-unleash-the-power-of-the-female-brain.epub"
  },
  {
    "id": "mind-self-the-upside-of-irrationality",
    "title": "The Upside of Irrationality",
    "author": "Dan Ariely",
    "collection": "Mind & Self",
    "wing": "Mind & Self",
    "genre": "Mind & Self",
    "order": 7,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "mind-self-the-upside-of-irrationality.epub"
  },
  {
    "id": "mind-self-promote-yourself",
    "title": "Promote Yourself",
    "author": "Dan Schawbel",
    "collection": "Mind & Self",
    "wing": "Mind & Self",
    "genre": "Mind & Self",
    "order": 8,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "mind-self-promote-yourself.epub"
  },
  {
    "id": "ai-technology-the-beginners-guide-to-ai",
    "title": "The Beginner's Guide to AI",
    "author": "Anthem Publishing",
    "collection": "AI & Technology",
    "wing": "AI & Technology",
    "genre": "AI & Technology",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "navy",
    "size": "tall",
    "format": "PDF",
    "file": null,
    "private": true,
    "storagePath": "ai-technology-the-beginners-guide-to-ai.pdf"
  },
  {
    "id": "ai-technology-the-ai-book",
    "title": "The AI Book",
    "author": "Susanne Chishti, Ivana Bartoletti, Anne Leslie & Shân M. Millie",
    "collection": "AI & Technology",
    "wing": "AI & Technology",
    "genre": "AI & Technology",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "plum",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "ai-technology-the-ai-book.epub"
  },
  {
    "id": "ai-technology-simply-artificial-intelligence",
    "title": "Simply Artificial Intelligence",
    "author": "Dorling Kindersley",
    "collection": "AI & Technology",
    "wing": "AI & Technology",
    "genre": "AI & Technology",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "sage",
    "size": "short",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "ai-technology-simply-artificial-intelligence.epub"
  },
  {
    "id": "business-leadership-hbr-10-must-reads-executives",
    "title": "HBR's 10 Must Reads for Executives: 8-Volume Collection",
    "author": "Harvard Business Review",
    "collection": "Business & Leadership",
    "wing": "Business & Leadership",
    "genre": "Business & Leadership",
    "order": 1,
    "status": "to-read",
    "favorite": false,
    "spine": "oxblood",
    "size": "tall",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "business-leadership-hbr-10-must-reads-executives.epub"
  },
  {
    "id": "business-leadership-the-busy-leaders-handbook",
    "title": "The Busy Leader's Handbook",
    "author": "Quint Studer",
    "collection": "Business & Leadership",
    "wing": "Business & Leadership",
    "genre": "Business & Leadership",
    "order": 2,
    "status": "to-read",
    "favorite": false,
    "spine": "brown",
    "size": "medium",
    "format": "EPUB",
    "file": null,
    "private": true,
    "storagePath": "business-leadership-the-busy-leaders-handbook.epub"
  },
  {
    "id": "business-leadership-the-leadership-challenge",
    "title": "The Leadership Challenge",
    "author": "James M. Kouzes & Barry Z. Posner",
    "collection": "Business & Leadership",
    "wing": "Business & Leadership",
    "genre": "Business & Leadership",
    "order": 3,
    "status": "to-read",
    "favorite": false,
    "spine": "forest",
    "size": "tall",
    "format": "PDF",
    "file": null,
    "private": true,
    "storagePath": "business-leadership-the-leadership-challenge.pdf"
  }
];