window.MIDNIGHT_BOOKS = [
  {
    id: "dorian-gray",
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    genre: "Classics",
    year: 1890,
    status: "to-read",
    favorite: true,
    spine: "oxblood",
    size: "tall",
    file: null,
    note: "Demo shelf entry — add a PDF later."
  },
  {
    id: "frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Gothic",
    year: 1818,
    status: "to-read",
    favorite: false,
    spine: "forest",
    size: "medium",
    file: null,
    note: "Demo shelf entry — add a PDF later."
  },
  {
    id: "dracula",
    title: "Dracula",
    author: "Bram Stoker",
    genre: "Gothic",
    year: 1897,
    status: "to-read",
    favorite: false,
    spine: "wine",
    size: "tall",
    file: null,
    note: "Demo shelf entry — add a PDF later."
  },
  {
    id: "jane-eyre",
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    genre: "Classics",
    year: 1847,
    status: "reading",
    favorite: true,
    spine: "navy",
    size: "medium",
    file: null,
    note: "Demo shelf entry — add a PDF later."
  },
  {
    id: "crime-punishment",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genre: "Classics",
    year: 1866,
    status: "to-read",
    favorite: false,
    spine: "brown",
    size: "tall",
    file: null,
    note: "Demo shelf entry — add a PDF later."
  },
  {
    id: "wuthering-heights",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    genre: "Classics",
    year: 1847,
    status: "read",
    favorite: true,
    spine: "sage",
    size: "short",
    file: null,
    note: "Demo shelf entry — add a PDF later."
  },
  {
    id: "metamorphosis",
    title: "The Metamorphosis",
    author: "Franz Kafka",
    genre: "Classics",
    year: 1915,
    status: "read",
    favorite: false,
    spine: "charcoal",
    size: "short",
    file: null,
    note: "Demo shelf entry — add a PDF later."
  },
  {
    id: "little-women",
    title: "Little Women",
    author: "Louisa May Alcott",
    genre: "Classics",
    year: 1868,
    status: "to-read",
    favorite: false,
    spine: "plum",
    size: "medium",
    file: null,
    note: "Demo shelf entry — add a PDF later."
  }
];